# Generated by Django 2.0.13 on 2019-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20190311_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
