# Generated by Django 2.0.13 on 2019-03-11 20:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20190311_1536'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='venda',
            managers=[
                ('myobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
