# Generated by Django 2.0.13 on 2019-03-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20190311_2057'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='venda',
            managers=[
            ],
        ),
    ]
