# Generated by Django 2.0.13 on 2019-03-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20190317_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar param NFe'), ('ver_dashboard', 'Ver o Dasjboard'))},
        ),
    ]
