# Generated by Django 2.0.13 on 2019-03-11 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20190311_0235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItensDoProduto',
            new_name='ItensDoPedido',
        ),
    ]
